my_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

print(my_tuple[0])
print(my_tuple[1])
print(my_tuple[2])
print(my_tuple[3])
print(my_tuple[4])
print(my_tuple[5])
print(my_tuple[6])
print(my_tuple[7])
print(my_tuple[8])
print(my_tuple[9])